language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

before_script: composer install --prefer-source

script: phpunit -c tests/phpunit.travis.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
